### ISSUE TITLE
Dojo 7 Prep

### ISSUE THREAD

**Issue by KaneFreeman** [dojo/site#210]
- [ ] Update site to Dojo 7 (#209)
- [x] Update documentation repo branch (#207)
- [x] Publish Dojo 7 docs to next.dojo.io (#207)
- [ ] After Dojo 7 release
   - [ ] Create `v7` branch and move onto dojo.io domain
   - [ ] Move `v6` onto v6.dojo.io domain

**Comment by agubler** [comment]
I think this has been completed! @KaneFreeman please feel free to correct me if I am wrong 😄
